name = "be"
compatibility_date = "2024-09-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
# MY_VAR = "my-variable"
POCKETBASE_URL = "http://127.0.0.1:8090"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"